---
# Restrict developers to logging in to only the jump server and the ocpmaster servers
#

- name: Create the admin_allow_all rule for Realm and Satellite Administrators
  ipa_hbacrule:
    name: admin_allow_all
    description: "Realm Admin accesses all hosts"
    state: present
    ipa_host: "{{ hostname }}"
    ipa_user: "admin"
    ipa_pass: "{{ idm_admin_password }}"
    hostcategory: all
    servicecategory: all
    usergroup: 
    - admins
    - satgroup-administrator

- name: Create an OCP POC users HBAC rule
  ipa_hbacrule:
    name: ocp-poc-users
    description: "Restrict access to ocpmasters"
    state: present
    ipa_host: "{{ hostname }}"
    ipa_user: "admin"
    ipa_pass: "{{ idm_admin_password }}"
    hostgroup:
    - ocp-masters
    - util-servers
    servicecategory: all
    usergroup:
    - ocpgroup-developer
    - ocpgroup-proj_administrator

- name: Create an OCP Admins HBAC rule
  ipa_hbacrule:
    name: ocp-admins
    description: "OCP Admins can access to ocp masters, nodes, routers, load balancers and utility servers"
    state: present
    ipa_host: "{{ hostname }}"
    ipa_user: "admin"
    ipa_pass: "{{ idm_admin_password }}"
    hostgroup:
    - ocp-masters
    - ocp-servers
    - util-servers
    servicecategory: all
    usergroup:
    - ocpgroup-operator
    - ocpgroup-cluster_administrator

- name: Create a Sat Operators HBAC rule
  ipa_hbacrule:
    name: sat-operators
    description: "Satellite Operators can access the Satellite and Capsule Servers"
    state: present
    ipa_host: "{{ hostname }}"
    ipa_user: "admin"
    ipa_pass: "{{ idm_admin_password }}"
    hostgroup:
    - sat-servers
    servicecategory: all
    usergroup:
    - satgroup-operators

- name: Create a CFME Operators HBAC rule
  ipa_hbacrule:
    name: cfme-operators
    description: "Satellite Operators can access the Satellite and Capsule Servers"
    state: present
    ipa_host: "{{ hostname }}"
    ipa_user: "admin"
    ipa_pass: "{{ idm_admin_password }}"
    hostgroup:
    - cfme-servers
    servicecategory: all
    usergroup:
    - evmgroup-super_administrator
    - evmgroup-administrator
    - evmgroup-operator

- name: Create a AWX Operators HBAC rule
  ipa_hbacrule:
    name: cfme-operators
    description: "Satellite Operators can access the Satellite and Capsule Servers"
    state: present
    ipa_host: "{{ hostname }}"
    ipa_user: "admin"
    ipa_pass: "{{ idm_admin_password }}"
    hostgroup:
    - awx-servers
    servicecategory: all
    usergroup:
    - towergroup-administrator
    - towergroup-operator

- name: Disable the allow_all rule
  ipa_hbacrule:
    name: allow_all
    state: disabled
    ipa_host: "{{ hostname }}"
    ipa_user: "admin"
    ipa_pass: "{{ idm_admin_password }}"

