---
# add standard users in a POC
# 

- name: add basic POC admin and developer users
  command: "echo {{ default_password }} | ipa user-add {{ item.login }} --first {{ item.first }} --last {{ item.last }}"
  with_items:
    - { login: "poc_admin", first: "POC", last: "Admin" }
    - { login: "developer1", first: "Developer", last: "One" }
    - { login: "developer2", first: "Developer", last: "Two" }
    - { login: "developer3", first: "Developer", last: "Three" }

- name: add any additional users required
  command: echo {{ default_password }} | ipa user-add {{ item.login }} --first {{ item.first }} --last {{ item.last }}
  with_items: "{{ additional_users }}"
  when: additional_users is defined

- name: add basic POC members to groups
  command: ipa group-add-member {{ item.group }} {{ item.flag }}"{{ item.value }}"
  with_items:
    - { group: "admins", flag: "--users=", value: "poc_admin" }
    - { group: "ocpgroup-developer", flag: "--users=", value: "developer1" }
    - { group: "ocpgroup-developer", flag: "--users=", value: "developer2" }
    - { group: "ocpgroup-developer", flag: "--users=", value: "developer3" }
    - { group: "evmgroup-super_administrator", flag: "--groups=", value: "admins" }
    - { group: "satgroup-administrator", flag: "--groups=", value: "admins" }
    - { group: "towergroup-administrator", flag: "--groups=", value: "admins" }
    - { group: "ocpgroup-cluster_administrator", flag: "--groups=", value: "admins" }

- name: add any additional users to groups
  command: ipa group-add-member {{ item.group }} {{ item.options }}
  with_subelements: 
    - "{{ additional_users }}"
    - groups
  when: additional_users is defined


